# Generated by Django 5.1.7 on 2025-03-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='invoice',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Invoice Name'),
        ),
        migrations.AddField(
            model_name='item',
            name='quote',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Quote Name'),
        ),
    ]
