# Generated by Django 5.1.7 on 2025-03-09 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_remove_invoice_item_remove_quote_item_and_more'),
        ('product', '0002_item_invoice_item_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.invoice'),
        ),
        migrations.AlterField(
            model_name='item',
            name='quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.quote'),
        ),
    ]
