# Generated by Django 5.1.7 on 2025-03-12 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_item_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='total_price',
            field=models.FloatField(default=0, editable=False, verbose_name='Total Price'),
        ),
    ]
