# Generated by Django 5.1.7 on 2025-03-12 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_item_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='total_price',
            new_name='item_price',
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Product Price'),
        ),
    ]
