# Generated by Django 5.1.7 on 2025-03-12 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_rename_total_price_item_item_price_alter_item_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='price',
        ),
        migrations.AlterField(
            model_name='item',
            name='item_price',
            field=models.FloatField(default=0, editable=False, verbose_name='Item Price'),
        ),
    ]
