# Generated by Django 5.1.7 on 2025-03-12 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_remove_item_price_alter_item_item_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProducerCategory',
            new_name='ProductCategory',
        ),
        migrations.RenameModel(
            old_name='ProducerGroup',
            new_name='ProductGroup',
        ),
    ]
