# Generated by Django 5.1.7 on 2025-03-12 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_rename_producercategory_productcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_price',
            field=models.FloatField(default=0, verbose_name='Item Price'),
        ),
    ]
