# Generated by Django 5.1.7 on 2025-03-12 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_item_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='total_price',
            field=models.FloatField(default=0, verbose_name='Total Price'),
        ),
    ]
