# Generated by Django 5.1.7 on 2025-03-13 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_alter_invoice_discount_alter_invoice_final_price_and_more'),
        ('product', '0011_item_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_price',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True, verbose_name='Item Price'),
        ),
        migrations.AlterField(
            model_name='item',
            name='quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='order.quote'),
        ),
        migrations.AlterField(
            model_name='item',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True, verbose_name='Total Price'),
        ),
        migrations.AlterField(
            model_name='pricebook',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True, verbose_name='Price Book Discount'),
        ),
        migrations.AlterField(
            model_name='pricebook',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True, verbose_name='Price Book'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tax',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20, null=True, verbose_name='Product Tax'),
        ),
    ]
