# Generated by Django 5.1.7 on 2025-04-09 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_item_comment_alter_item_item_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Name')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='Duration')),
                ('starts_at', models.DateTimeField(auto_now_add=True, verbose_name='Starts at')),
            ],
            options={
                'verbose_name': 'Package',
                'verbose_name_plural': 'Packages',
                'db_table': 'package',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.package'),
        ),
    ]
