# Generated by Django 5.1.7 on 2025-04-09 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_package_item_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='starts_at',
            field=models.DateTimeField(verbose_name='Starts at'),
        ),
    ]
