# Generated by Django 5.1.7 on 2025-04-09 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_quote_price_after_discount'),
        ('product', '0016_alter_package_starts_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='description',
            field=models.TextField(default='test', max_length=500, verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.quote'),
        ),
    ]
