# Generated by Django 5.1.7 on 2025-04-09 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_quote_price_after_discount'),
        ('product', '0017_package_description_package_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Total'),
        ),
        migrations.AddField(
            model_name='package',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='item',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='product.package'),
        ),
        migrations.AlterField(
            model_name='package',
            name='quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages', to='order.quote'),
        ),
    ]
