# Generated by Django 5.1.7 on 2025-04-09 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_package_total_price_package_unit_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(default='GB', max_length=25, verbose_name='Unit'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='package',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Unit Price'),
        ),
    ]
