# Generated by Django 5.1.7 on 2025-04-09 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_product_unit_alter_package_unit_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_no',
        ),
    ]
