# Generated by Django 5.1.7 on 2025-03-15 08:52

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_created_at_user_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='updated_at',
            field=django_jalali.db.models.jDateTimeField(auto_now=True),
        ),
    ]
