# Generated by Django 5.1.7 on 2025-03-15 08:53

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_company_created_at_alter_company_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='created_at',
            field=django_jalali.db.models.jDateField(auto_now_add=True),
        ),
    ]
