# Generated by Django 5.1.7 on 2025-03-09 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Potential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=255, verbose_name='Potential name')),
                ('description', models.CharField(max_length=255, verbose_name='Potential description')),
                ('status', models.CharField(max_length=255, verbose_name='Potential status')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
            options={
                'verbose_name': 'Potential',
                'verbose_name_plural': 'Potentials',
                'db_table': 'potential',
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('subject', models.CharField(max_length=50, verbose_name='Quote subject')),
                ('stage', models.IntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Cancelled'), (3, 'Sent'), (4, 'Paid'), (5, 'Expired'), (6, 'Processing'), (7, 'Rejected'), (8, 'Completed')], default=0, verbose_name='Quote stage')),
                ('status', models.BooleanField(default=True, verbose_name='Quote status')),
                ('address', models.CharField(max_length=255, verbose_name='Quote address')),
                ('description', models.CharField(max_length=255, verbose_name='Quote description')),
                ('terms_conditions', models.CharField(max_length=255, verbose_name='Quote terms conditions')),
                ('export_file', models.FileField(blank=True, null=True, upload_to='', verbose_name='Quote export file')),
                ('total_price', models.FloatField(blank=True, null=True, verbose_name='Local price')),
                ('tax', models.FloatField(blank=True, null=True, verbose_name='Tax')),
                ('discount', models.FloatField(blank=True, null=True, verbose_name='Discount')),
                ('discount_rate', models.IntegerField(blank=True, null=True, verbose_name='Discount rate')),
                ('final_price', models.FloatField(blank=True, null=True, verbose_name='Final price')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
                ('potential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.potential')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
            options={
                'verbose_name': 'Quote',
                'verbose_name_plural': 'Quotes',
                'db_table': 'quote',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('subject', models.CharField(max_length=50, verbose_name='Invoice subject')),
                ('stage', models.IntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Cancelled'), (3, 'Sent'), (4, 'Paid'), (5, 'Expired'), (6, 'Processing'), (7, 'Rejected'), (8, 'Completed')], default=0, verbose_name='Invoice stage')),
                ('is_active', models.BooleanField(default=True, verbose_name='Invoice status')),
                ('address', models.CharField(max_length=255, verbose_name='Invoice address')),
                ('description', models.CharField(max_length=255, verbose_name='Invoice description')),
                ('terms_conditions', models.CharField(max_length=255, verbose_name='Invoice terms conditions')),
                ('export_file', models.FileField(blank=True, null=True, upload_to='', verbose_name='Invoice export file')),
                ('total_price', models.FloatField(blank=True, null=True, verbose_name='Local price')),
                ('tax', models.FloatField(blank=True, null=True, verbose_name='Tax')),
                ('discount', models.FloatField(blank=True, null=True, verbose_name='Discount')),
                ('discount_rate', models.IntegerField(blank=True, null=True, verbose_name='Discount rate')),
                ('final_price', models.FloatField(blank=True, null=True, verbose_name='Final price')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
                ('potential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.potential')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.quote')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'db_table': 'invoice',
            },
        ),
    ]
