# Generated by Django 5.1.7 on 2025-03-09 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_no',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Invoice number'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='quote',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order.quote'),
        ),
    ]
