# Generated by Django 5.1.7 on 2025-03-09 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_invoice_invoice_no_alter_invoice_quote'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.item'),
        ),
        migrations.AddField(
            model_name='quote',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.item'),
        ),
    ]
