# Generated by Django 5.1.7 on 2025-03-09 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_invoice_item_quote_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Draft'), (2, 'Pending'), (3, 'Approved'), (4, 'Rejected'), (5, 'Expired'), (6, 'Converted'), (7, 'Canceled')], default=2, verbose_name='Invoice status'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='stage',
            field=models.PositiveIntegerField(choices=[(1, 'Pending'), (2, 'Approved'), (3, 'Cancelled'), (4, 'Sent'), (5, 'Paid'), (6, 'Expired'), (7, 'Processing'), (8, 'Rejected'), (9, 'Completed')], default=1, verbose_name='Invoice stage'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='stage',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Approved'), (3, 'Cancelled'), (4, 'Sent'), (5, 'Paid'), (6, 'Expired'), (7, 'Processing'), (8, 'Rejected'), (9, 'Completed')], default=1, verbose_name='Quote stage'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Draft'), (2, 'Pending'), (3, 'Approved'), (4, 'Rejected'), (5, 'Expired'), (6, 'Converted'), (7, 'Canceled')], default=2, verbose_name='Quote status'),
        ),
    ]
