# Generated by Django 5.1.7 on 2025-03-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_invoice_status_alter_invoice_stage_alter_quote_stage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='item',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='item',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Draft'), (2, 'Pending'), (3, 'Approved'), (4, 'Rejected'), (5, 'Expired'), (6, 'Converted'), (7, 'Canceled')], default=1, verbose_name='Invoice status'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Draft'), (2, 'Pending'), (3, 'Approved'), (4, 'Rejected'), (5, 'Expired'), (6, 'Converted'), (7, 'Canceled')], default=1, verbose_name='Quote status'),
        ),
    ]
