# Generated by Django 5.1.7 on 2025-03-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_remove_invoice_item_remove_quote_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Quote status'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Total price'),
        ),
    ]
