# Generated by Django 5.1.7 on 2025-03-12 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_quote_is_active_alter_invoice_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='total_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Total price'),
        ),
    ]
