# Generated by Django 5.1.7 on 2025-03-12 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_quote_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='discount',
            field=models.FloatField(blank=True, editable=False, null=True, verbose_name='Discount'),
        ),
    ]
