# Generated by Django 5.1.7 on 2025-03-12 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_quote_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='potential',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.potential'),
        ),
    ]
