# Generated by Django 5.1.7 on 2025-03-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_alter_quote_potential'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='discount',
            field=models.FloatField(blank=True, null=True, verbose_name='Discount'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='total_price',
            field=models.FloatField(blank=True, default=0, verbose_name='Total price'),
        ),
    ]
