# Generated by Django 5.1.7 on 2025-03-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_alter_invoice_discount_alter_invoice_final_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Draft'), (2, 'Pending'), (3, 'Approved'), (4, 'Rejected'), (5, 'Expired'), (6, 'Converted'), (7, 'Cancelled')], default=1, verbose_name='Invoice status'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Draft'), (2, 'Pending'), (3, 'Approved'), (4, 'Rejected'), (5, 'Expired'), (6, 'Converted'), (7, 'Cancelled')], default=1, verbose_name='Quote status'),
        ),
    ]
