# Generated by Django 5.1.7 on 2025-03-16 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_alter_invoice_status_alter_quote_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='price_after_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True, verbose_name='Price after discount'),
        ),
    ]
